apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rcs1
  region: ap-northeast-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: rcs
      namespace: rcs-app
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::925517469638:policy/AmazonEKSClusterPodsPolicy"
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachRoleARN: "arn:aws:iam::925517469638:role/AmazonEKSClusterAutoscalerRole"
    attachPolicyARNs:
    - "arn:aws:iam::925517469638:policy/AmazonEKSClusterAutoscalerPolicy"
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    attachRoleARN: "arn:aws:iam::925517469638:role/AmazonEKSLoadBalancerControllerRole"
    attachPolicyARNs:
    - "arn:aws:iam::925517469638:policy/AWSLoadBalancerControllerIAMPolicy"

vpc:
  id: "vpc-7d6cc414"
  securityGroup: "sg-0e53286f6090c9930"
  subnets:
    public:
      ap-northeast-2a: {id: subnet-ef04ae86}
      ap-northeast-2c: {id: subnet-89e217c4}
    private:
      ap-northeast-2a: {id: subnet-06ec67e561756d7c0}
      ap-northeast-2b: {id: subnet-02062889999b1ea3d}
      ap-northeast-2c: {id: subnet-06990378050340147}

managedNodeGroups:
  - name: ng-2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        autoScaler: true
    minSize: 1
    maxSize: 3
    instanceType: t3.medium
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    subnets:
      - subnet-06ec67e561756d7c0
      - subnet-02062889999b1ea3d
      - subnet-06990378050340147