apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harmony
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/log
  - replicasets
  - replicasets/log
  verbs:
  - patch
  - get
  - list
  - watch
  - log