# Datadog Agent with Logs, APM, Processes, and System Probe enabled

targetSystem: "linux"
datadog:
  # apiKey: <DATADOG_API_KEY>
  # appKey: <DATADOG_APP_KEY>
  # If not using secrets, then use apiKey and appKey instead
  # apiKeyExistingSecret: <DATADOG_API_KEY_SECRET>
  # appKeyExistingSecret: <DATADOG_APP_KEY_SECRET>
  site: us3.datadoghq.com
  clusterName: rcs
  tags: []
  # datadog.kubelet.tlsVerify should be `false` on kind and minikube
  # to establish communication with the kubelet
  # kubelet:
    # tlsVerify: "false"
  logs:
    enabled: true
    containerCollectAll: true
    # containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false

